"""empty message

Revision ID: 50ae9aab8b27
Revises: 938adc0c2548
Create Date: 2022-04-12 16:15:47.439941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ae9aab8b27'
down_revision = '938adc0c2548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aquarium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('fish', sa.String(length=200), nullable=False),
    sa.Column('plants', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=5), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aquarium')
    # ### end Alembic commands ###
